CREATE TABLE invoice (
	id serial PRIMARY KEY,
	number TEXT NOT NULL,
    vendor TEXT NOT NULL,
    vendor_tax_registration_number VARCHAR(20) NOT NULL,
    vendor_bank_details VARCHAR(20) NOT NULL,
    vendor_address TEXT,
    billing_address TEXT,
    po_number VARCHAR(50),
    date_of_issue DATE,
    payment_terms INT,
    due_date DATE,
    description TEXT,
    line_item_details TEXT,
    pre_tax_amount NUMERIC(10,2),
    discount NUMERIC(10,2),
    tax_amount NUMERIC(10,2),
    total_amount NUMERIC(10,2),
    gl_code VARCHAR(10),
    cost_centre TEXT,
    currency VARCHAR(3) DEFAULT 'EUR',
	status TEXT NOT NULL DEFAULT 'TO_BE_VALIDATED'
);
